version: '3.9'
services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - '5001:5001'

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - '3000:80'
    depends_on:
      - server
